var popupoverlay=document.querySelector(".popup-overlay")
var popupbox=document.querySelector(".popup-box")
var contactButton=document.getElementById("contact")


// Display the contact page
contactButton.addEventListener("click",function(){
    popupoverlay.style.display="block"
    popupbox.style.display="block"
})

var sendbutton=document.getElementById("send")

// Control of send and cancel
sendbutton.addEventListener("click",function(event)
{
    event.preventDefault()
    popupoverlay.style.display="none"
    popupbox.style.display="none"
})

var cancelbutton=document.getElementById("cancel")

cancelbutton.addEventListener("click",function(event){
    event.preventDefault()
    popupoverlay.style.display="none"
    popupbox.style.display="none"
})


var sendbutton = document.getElementById("send");

sendbutton.addEventListener("click", function(event) {
    event.preventDefault();

    // Get form data
    var name = document.querySelector(".name").value;
    var email = document.querySelector(".email").value;
    var message = document.querySelector(".message").value;

    // Prepare the message to send
    var telegramMessage = `Name: ${name}\nEmail: ${email}\nMessage: ${message}`;

    // Telegram Bot Token and Chat ID
    var botToken = "7914568011:AAGJV3odrv49nJIzJmgbWR41VuyXmSXoCFY"; //bot token generated by fatherbot telegram
    var chatId = "5181502452"; // your actual chat ID

    // Telegram API URL
    var telegramURL = `https://api.telegram.org/bot${botToken}/sendMessage`;

    // Send the data to Telegram
    fetch(telegramURL, {
        method: "POST",
        headers: {
            "Content-Type": "application/json"
        },
        body: JSON.stringify({
            chat_id: chatId,
            text: telegramMessage
        })
    })
    .then(response => response.json())
    .then(data => {
        if (data.ok) {
            alert("Message sent successfully!");
        } else {
            alert("Error sending message.");
        }
    })
    .catch(error => {
        console.error("Error:", error);
    });

    // Close the popup after sending
    popupoverlay.style.display = "none";
    popupbox.style.display = "none";
});

// Scroll the window to the top
var ScrollToTop=document.getElementById("ScrollToTop");

window.onscroll=function()
{
    if(document.body.scrollTop > 100 || document.documentElement.scrollTop >100){
        ScrollToTop.style.display="block";
    }
    else{
        ScrollToTop.style.display="none";
    }
};

ScrollToTop.onclick = function(event){
    event.preventDefault();
    window.scrollTo({top: 0,behavior: 'smooth'});
};